import "../styles/globals.css";

import type { AppProps } from "next/app";
import Head from "next/head";
import React from "react";
import { Toaster } from "react-hot-toast";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>nirvana | virtual office</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/1024x1024.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={"true"}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="min-h-screen min-w-screen bg-zinc-700 flex flex-col">
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
