enum SocketChannels {
  JOIN_ROOM = "JOIN_ROOM",
  SEND_AUDIO_CLIP = "SEND_AUDIO_CLIP",
  SEND_USER_STATUS_UPDATE = "SEND_USER_STATUS_UPDATE",
  SEND_STARTED_SPEAKING = "SEND_STARTED_SPEAKING",
  SEND_STOPPED_SPEAKING = "SEND_STOPPED_SPEAKING",
}

export default SocketChannels;
