enum SocketChannels {
  JOIN_ROOM = "JOIN_ROOM",
  SEND_AUDIO_CLIP = "SEND_AUDIO_CLIP",
  SEND_USER_STATUS_UPDATE = "SEND_USER_STATUS_UPDATE",

  SEND_STARTED_SPEAKING_TO_SERVER = "SEND_STARTED_SPEAKING_TO_SERVER",
  SEND_STOPPED_SPEAKING_TO_SERVER = "SEND_STOPPED_SPEAKING_TO_SERVER",

  SEND_STARTED_SPEAKING_TO_CLIENT = "SEND_STARTED_SPEAKING_TO_CLIENT",
  SEND_STOPPED_SPEAKING_TO_CLIENT = "SEND_STOPPED_SPEAKING_TO_CLIENT",
}

export default SocketChannels;
