enum SocketChannels {
  JOIN_ROOM = "JOIN_ROOM",
  SEND_AUDIO_CLIP = "SEND_AUDIO_CLIP",
  SEND_USER_STATUS_UPDATE = "SEND_USER_STATUS_UPDATE",

  SEND_STARTED_SPEAKING = "SEND_STARTED_SPEAKING",
  SEND_STOPPED_SPEAKING = "SEND_STOPPED_SPEAKING",

  JOIN_LIVE_ROOM = "JOIN_LIVE_ROOM",
  GET_ALL_ACTIVE_SOCKET_IDS = "GET_ALL_ACTIVE_SOCKET_IDS",

  SEND_SIGNAL = "SEND_SIGNAL",

  RECEIVE_SIGNAL = "RECEIVE_SIGNAL",
}

export default SocketChannels;
